package com.group7.g7_trivia_game.database.entities;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import com.group7.g7_trivia_game.database.TriviaDatabase;

import java.util.Objects;

/**
 * User object for storing in database.
 *
 * @author Rawley Lizarraga
 * @since 7/31/2025
 */
@Entity(tableName = TriviaDatabase.USER_TABLE)
public class User {
    @PrimaryKey(autoGenerate = true)
    private int id;
    private String username;
    private String password;
    private boolean isAdmin;
    private int score;

    /**
     * Initializes a new User object using given username and password.
     * Default sets isAdmin to false and score to 0.
     * @param username User's username as String
     * @param password User's password as String
     */
    public User(String username, String password) {
        this.username = username;
        this.password = password;
        this.isAdmin = false;
        this.score = 0;
    }

    /**
     * Adds given int to existing user score.
     * @param scoreAddition int to to add to User's score.
     */
    public void addScore(int scoreAddition){
        this.score += scoreAddition;
    }

    //AUTOGENERATED BELOW THIS LINE

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isAdmin() {
        return isAdmin;
    }

    public void setAdmin(boolean admin) {
        isAdmin = admin;
    }

    public int getScore() {
        return score;
    }

    public void setScore(int score) {
        this.score = score;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return id == user.id && isAdmin == user.isAdmin && score == user.score && Objects.equals(username, user.username) && Objects.equals(password, user.password);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, username, password, isAdmin, score);
    }
}
